### ISSUE TITLE
Display paragraph breaks in story submission

### ISSUE THREAD

**Issue by litnerdy** [techforwarren/two-cent-stories#42]
**Problem**: Currently, when you submit a story it is shown as plain text. Even line breaks are removed.

**Proposal**: We should at _minimum_ allow for display of line breaks (markdown would also be great but not needed if that's difficult to implement).

**Impact**: Right now, it's difficult to read the blocks of text that result from story submission. Since the stories are the heart of this site, we need to make them easy to read.

**Wish**: Ideally we'd have a full on 'wysiwyg (what you see is what you get) text editor, for ease of use by non-technical audiences, but that's definitely not mandatory.

**Comment by joegoldbeck** [comment]
Oh darn! That's annoying. We should definitely allow line breaks! (I assume that's what you mean by "paragraph breaks")

wysiwyg is definitely out of scope.

markdown could be possible but I'm skeptical of doing it without a "preview" feature which would be a bit more work

**Comment by litnerdy** [comment]
Agreed - let's go with just showing the line breaks for now.

**Comment by joziesands** [comment]
None of the dev server stories have line breaks, but here's a screen shot of Eva's story with the fix. 
<img width="671" alt="Screen Shot 2020-02-24 at 2 13 02 PM" src="https://user-images.githubusercontent.com/1656339/75187634-0ef12780-5710-11ea-9bf2-327f2bce4db7.png">
